### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by Sanjeev-Kumar78** [Sanjeev-Kumar78/Farewell_Invitation#2]
# Issue in Phones
<img align="right" src="https://user-images.githubusercontent.com/62820550/216782794-f39e5eef-0e39-4e23-9ae8-405fd6ce716c.png"/>

* card elements
* No adjustments
* No border

All the above are having issues.

**Comment by shyamtawli** [comment]
I can work on this if you want, Assign me and I will try to make chances in 24 hrs.

**Comment by Starboy-Sharma** [comment]
There are two reasons for this behavior as I have checked your code

- You have made your body display flex. That's why your footer is not aligned
- The other problem is coming from this CSS property `backdrop-filter: saturate(180%) blur(10px);`

For more information, you can check this [article](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers)

**Comment by Sanjeev-Kumar78** [comment]
@Starboy-Sharma @shyamtawli 
Thank you very much to both of you.
I actually didn't think that anyone would help me with this issue.
![6a0ac420cd900379cbe1beff5127fd42.gif](https://user-images.githubusercontent.com/62820550/216818483-42be34b2-759a-4326-86f5-da1a0e6b62bf.gif)

**Comment by shyamtawli** [comment]
Hey @Sanjeev-Kumar78 Sorry but I was busy doing something else.
